//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// Generates a safe wrapper for Layers.
/// </summary>
namespace Aty 
{ 
 public static class Layers
{
    public static readonly string Default = "Default";
    public static readonly string TransparentFX = "TransparentFX";
    public static readonly string IgnoreRaycast = "IgnoreRaycast";
    public static readonly string Water = "Water";
    public static readonly string UI = "UI";
} 
 } 