//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// Generates a safe wrapper for Layers.
/// </summary>
namespace Aty 
{ 
 public enum Layers
{
    Default,
    TransparentFX,
    IgnoreRaycast,
    Water,
    UI,
} 
 } 