//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// Generates a safe wrapper for SceneNames.
/// </summary>
namespace Aty 
{ 
 public static class SceneNames
{
    public static readonly string Menu = "Menu";
    public static readonly string Labrinth = "Labrinth";
} 
 } 