//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// Generates a safe wrapper for Tags.
/// </summary>
namespace Aty 
{ 
 public static class Tags
{
    public static readonly string Untagged = "Untagged";
    public static readonly string Respawn = "Respawn";
    public static readonly string Finish = "Finish";
    public static readonly string EditorOnly = "EditorOnly";
    public static readonly string MainCamera = "MainCamera";
    public static readonly string Player = "Player";
    public static readonly string GameController = "GameController";
} 
 } 